### PR TITLE
Bugfix: #36

### LINKED ISSUE #36: Selecting blank Artista for Lote unhandled
```
TypeError: Cannot read property 'value' of undefined
ObrasGroup.handleSelectChange
src/components/obras/ObrasGroup.jsx:33
  30 |   this.props.removeObraFromGroup(id);
  31 | }
  32 | 
> 33 | handleSelectChange(event) {
  34 |   const id = event.target.options[event.target.selectedIndex].value;
  35 | 
  36 |   const { value: { artista, medium, title, year } } = this.props.allObras.find( obra => obra.key === id );
```

### PR DESCRIPTION
**Pull request by varffs**
Fixes #36

### CODE REVIEW

**Comment by mixcas** [comment]
Actually i see an error on the way handleArtistaChange works:
```
handleArtistaChange({id, name}) {
    if(id !== undefined || id !== '') {
      this.setState({
        artista: {
          id,
          name,
        },
      });
    }
  }
```

**Comment by mixcas** [comment]
@varffs jsut double checking w u, do we actually need this condition? `if(id !== undefined || id !== '')`

**Comment by varffs** [comment]
Oh I see. No I think we don't need it but somehow empty `id`s seem to be passing thru it anyhow?

**Comment by mixcas** [comment]
i think the condition is wrong since the beginning, it would have a lil sense if it was AND instead of OR

**Pull request merged**
