### PR TITLE
Scaffold lotes

### PR DESCRIPTION
**Pull request by mikeyrayvon**
need to define how obras data is saved on the lote

### CODE REVIEW

**Comment by mikeyrayvon** [comment]
I put some work into this. now the `<ObrasGroup />` component is reading the `selectedObras` from `state.obrasGroup` on the `<LoteForm />`, and using that to render data, rather than keeping a duplicate on `<ObrasGroup />`

**Comment by mikeyrayvon** [comment]
It also filters out the `<select>` by the items in `props.selectedObras`

**Comment by mikeyrayvon** [comment]
Is there a reason for the string `obras` item were saving to the database here? Doesn't seem like we need it

**Comment by varffs** [comment]
No reason for `obras` string. 

@mixcas can you please check this on how to save the Obras group data.

**Comment by mikeyrayvon** [comment]
we talked about it yesterday and decided id & title for each was ok for now

**Comment by mikeyrayvon** [comment]
i merged master and added toasts

**Comment by mixcas** [comment]
I removed a bunch of code that that unused like `images` and `medium`. `images` will be added in a diff branch and `medium` need to be fixed in `artistas` first.

**Pull request merged**
